build:
    environment:
        php:
            version: 7.1
    tests:
        override:
            -
                command: 'bin/phpspec run'
                coverage:
                    file: 'coverage.xml'
                    format: 'php-clover'
filter:
    paths: ["src/*", "web/src/*"]
    excluded_paths:
        - "src/MainRoutingProvider.php"
        - "src/MainServiceProvider.php"
checks:
    php:
        code_rating: true
        duplication: false
    javascript: true
coding_style:
    php:
        spaces:
            before_parentheses:
                closure_definition: true
            around_operators:
                concatenation: true
        upper_lower_casing:
            keywords:
                general: lower
            constants:
                true_false_null: lower
