filter:
    paths: ["src/*", "web/src/*"]
    excluded_paths:
        - "src/MainRoutingProvider.php"
        - "src/MainServiceProvider.php"

checks:
    php:
        code_rating: true
        duplication: false
    javascript: true

coding_style:
    php:
        spaces:
            before_parentheses:
                closure_definition: true
            around_operators:
                concatenation: true
        upper_lower_casing:
            keywords:
                general: lower
            constants:
                true_false_null: lower

build:
    image: default-bionic
    environment:
        php:
            version: 8.1
            ini:
                'xdebug.mode': 'coverage'
    nodes:
        analysis:
            tests:
                override:
                    - php-scrutinizer-run
        my_tests_with_coverage:
            tests:
                override:
                  - command: 'bin/phpspec run'
                    coverage:
                        file: 'coverage.xml'
                        format: 'php-clover'
