#!/usr/bin/php
<?php declare(strict_types = 1);

use jschreuder\SpotDesk\ServiceContainer;

/** @var  ServiceContainer $container */
$container = require __DIR__ . '/config/app_init.php';

$application = new \Symfony\Component\Console\Application();

// user: namespace
$application->add(new jschreuder\SpotDesk\Command\CreateUserCommand($container->getAuthenticationService()));
$application->add(new \jschreuder\SpotDesk\Command\AssignUserToDepartmentCommand(
    $container->getUserRepository(), $container->getDepartmentRepository()
));

// mail: namespace
$application->add(new \jschreuder\SpotDesk\Command\CheckMailboxesCommand(
    $container->getMailboxRepository(),
    $container->getTicketRepository(),
    $container->getStatusRepository(),
    $container->getSendMailService(),
    $container->getUserRepository(),
    $container->getFetchMailService()
));
$application->add(new \jschreuder\SpotDesk\Command\SendMailingsCommand(
    $container->getTicketMailingRepository(), $container->getSendMailService()
));

// dev: namespace
$application->add(new \jschreuder\SpotDesk\Command\DevCreateFakerTicketsCommand(
    $container->getTicketRepository(), $container->getDepartmentRepository(), $container->getStatusRepository()
));
$application->add(new \jschreuder\SpotDesk\Command\DevCronCommand());

$application->run();
