#!/usr/bin/php
<?php declare(strict_types = 1);

/** @var  \Pimple\Container $container */
$container = require __DIR__ . '/etc/app_init.php';

$application = new \Symfony\Component\Console\Application();

$application->add(new jschreuder\SpotDesk\Command\CreateUserCommand($container['service.authentication']));

$application->run();
