#!/usr/bin/php
<?php declare(strict_types = 1);

/** @var  \Pimple\Container $container */
$container = require __DIR__ . '/config/app_init.php';

$application = new \Symfony\Component\Console\Application();

// user: namespace
$application->add(new jschreuder\SpotDesk\Command\CreateUserCommand($container['service.authentication']));
$application->add(new \jschreuder\SpotDesk\Command\AssignUserToDepartmentCommand(
    $container['repository.users'], $container['repository.departments']
));

// mail: namespace
$application->add(new \jschreuder\SpotDesk\Command\CheckMailboxesCommand(
    $container['repository.mailboxes'],
    $container['repository.tickets'],
    $container['repository.statuses'],
    $container['service.mail'],
    $container['repository.users']
));
$application->add(new \jschreuder\SpotDesk\Command\SendMailingsCommand(
    $container['repository.ticket_mailings'], $container['service.mail']
));

// dev: namespace
$application->add(new \jschreuder\SpotDesk\Command\DevCreateFakerTicketsCommand(
    $container['repository.tickets'], $container['repository.departments'], $container['repository.statuses']
));
$application->add(new \jschreuder\SpotDesk\Command\DevCronCommand());

$application->run();
